//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorize
    {
        public int ID_Autorize { get; set; }
        public string Logins { get; set; }
        public string Passwords { get; set; }
        public Nullable<int> Role_ID { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
