//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderSushiSets = new HashSet<OrderSushiSets>();
        }
    
        public int ID_Order { get; set; }
        public System.DateTime OrderDateTime { get; set; }
        public int TotalAmount { get; set; }
        public Nullable<int> PaymentMethod_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual PaymentMethods PaymentMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSushiSets> OrderSushiSets { get; set; }
    }
}
