//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika5
{
    using System;
    using System.Collections.Generic;
    
    public partial class SushiOrderSummary
    {
        public string SushiSetName { get; set; }
        public decimal SushiSetPrice { get; set; }
        public string PaymentMethod { get; set; }
        public System.DateTime OrderDateTime { get; set; }
    }
}
